# Generated by Django 5.0.3 on 2025-11-11 23:30

import django.db.models.deletion
from django.db import migrations, models


def generate_display_ids(apps, schema_editor):
    """Generate display_id for existing animals"""
    Animal = apps.get_model('api', 'Animal')
    
    # Group animals by type
    tipo_counts = {}
    
    for animal in Animal.objects.all().order_by('collar_id'):
        tipo = animal.tipo_animal
        if tipo not in tipo_counts:
            tipo_counts[tipo] = 0
        tipo_counts[tipo] += 1
        animal.display_id = f"{tipo}-{tipo_counts[tipo]:03d}"
        animal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='display_id',
            field=models.CharField(blank=True, editable=False, max_length=50, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='geocerca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='api.geocerca'),
        ),
        migrations.RunPython(generate_display_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='animal',
            name='display_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
