# Generated by Django 5.0.3 on 2025-11-19 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_animal_display_id_animal_geocerca'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='valor_registrado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertausuario',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('exportado', models.BooleanField(default=False)),
                ('fecha_exportacion', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='api.alerta')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
